### ISSUE TITLE
Installation fails, no such module: @polymer/test-runner 

### ISSUE THREAD

**Issue by developit** [PolymerLabs/template-instantiation#2]

**Comment by kenchris** [comment]
yes, I ran into the exact same.

**Comment by cdata** [comment]
Hey, sorry y'all. As you can probably tell this project is a little radioactive ATM. I'm going to try to firm it up a bit this weekend and make sure it can be installed cleanly from source, but be advised that the code within is subject to change in whimsical fashion.

**Comment by cdata** [comment]
This should be installable as of #6 - let me know if you keep having issues and I'll take another look!
